#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun  9 16:05:00 2020

@author: hannessuhr
"""


#file_name = './test_image_x_y_3/encoded_images.txt'
file_name = './test_image_numbered_greyscale/encoded_images.txt'
print(file_name)
file_object = open(file_name,'r')
encoded_raw = file_object.readlines()
file_object.close()
encoded = []

for index in range(1, len(encoded_raw), 1):
    print(index)
    if index % 2 == 0:
        print(index)
        enc_raw_splitted = encoded_raw[index].split(',')
        enc_raw_filtered = []
        
        for element in enc_raw_splitted:
            if not element == '' and not element == '\n':
                enc_raw_filtered.append(element)
                
        encoded.append(list(map(int,enc_raw_filtered)))
        #enc_raw_filtered = []
    else:
        image_name = encoded_raw[index].split(',')[0]
        encoded.append(image_name)